// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTimeOKCode is the HTTP code returned for type GetTimeOK
const GetTimeOKCode int = 200

/*GetTimeOK returns the time of the machine

swagger:response getTimeOK
*/
type GetTimeOK struct {

	/*the time of the machine
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTimeOK creates GetTimeOK with default headers values
func NewGetTimeOK() *GetTimeOK {

	return &GetTimeOK{}
}

// WithPayload adds the payload to the get time o k response
func (o *GetTimeOK) WithPayload(payload string) *GetTimeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get time o k response
func (o *GetTimeOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTimeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
