// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHostnameOKCode is the HTTP code returned for type GetHostnameOK
const GetHostnameOKCode int = 200

/*GetHostnameOK returns the hostname of the machine

swagger:response getHostnameOK
*/
type GetHostnameOK struct {

	/*the hostname of the machine
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetHostnameOK creates GetHostnameOK with default headers values
func NewGetHostnameOK() *GetHostnameOK {

	return &GetHostnameOK{}
}

// WithPayload adds the payload to the get hostname o k response
func (o *GetHostnameOK) WithPayload(payload string) *GetHostnameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hostname o k response
func (o *GetHostnameOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostnameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
