# swagger validate ./swagger/swagger.yml
swagger: "2.0"
info:
  title: 'Hello'
  version: '0.0.1'
paths:
  /hostname:
    get:
      operationId: 'getHostname'
      produces:
      - 'text/plain'
      responses:
        200:
          description: 'returns the hostname of the machine'
          schema:
            description: 'the hostname of the machine'
            type: 'string'
  /time:
      get:
        operationId: 'getTime'
        produces:
        - 'text/plain'
        responses:
          200:
            description: 'returns the time of the machine'
            schema:
              description: 'the time of the machine'
              type: 'string'