// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Pets

    Schemes:
      http
    Host: localhost
    BasePath: /example
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
